package com.finki.mojmentor.bootstrap;

import com.finki.mojmentor.Model.Mentor;
import com.finki.mojmentor.Model.MentorshipProgram;
import com.finki.mojmentor.Model.enumerations.Role;
import com.finki.mojmentor.service.UserService;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Service;

import javax.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;

@Component
@Service
public class DataHolder {
    public static List<Mentor> mentorList = new ArrayList<>();
    public static List<MentorshipProgram> mentroshipProgramsList = new ArrayList<>();
    private final UserService userService;

    public DataHolder(UserService userService) {
        this.userService = userService;
    }

    @PostConstruct
    public void init(){

        //Da se napravi lista za mentorshipPlatforms
        /*mentorList.add(new Mentor("Yale","Marler","ymarler0","gCUbOB9T","1979-06-06","ymarler0@pen.io","Male","9160 Walton Trail"));
        mentorList.add(new Mentor("Esdras","Travis","etravis1","ilF9i6DtDXbE","1971-12-10","etravis1@cdbaby.com","Female","91367 Hermina Avenue"));
        mentorList.add(new Mentor("Mel","Babcock","mbabcock2","Go1Pd52sn","1993-08-03","mbabcock2@epa.gov","Female","6 Aberg Terrace"));
        mentorList.add(new Mentor("Creight","Gepp","cgepp3","GmaMQkTFiM","1985-12-01","cgepp3@apache.org","Male","45 Corben Avenue"));
        mentorList.add(new Mentor("Wake","Baldi","wbaldi4","3ad5o8Rum","1992-03-14","wbaldi4@geocities.jp","Male","071 Transport Court"));
        mentorList.add(new Mentor("Nels","Ferrari","nferrari5","dJIEZk4SK1","1978-03-16","nferrari5@sohu.com","Female","7 Pleasure Court"));
        mentorList.add(new Mentor("Duky","Colles","dcolles6","w8l6uCfW","1971-06-10","dcolles6@hubpages.com","Male","30 Fair Oaks Avenue"));
        mentorList.add(new Mentor("Allister","Bonnin","abonnin7","LJy4Mb82","1989-08-27","abonnin7@bloomberg.com","Female","87869 Esch Point"));
        mentorList.add(new Mentor("Henri","Bedward","hbedward8","okteQ8","1987-09-03","hbedward8@archive.org","Male","473 Stephen Plaza"));
        mentorList.add(new Mentor("Gauthier","Hearl","ghearl9","Orh4BWil","1979-07-23","ghearl9@csmonitor.com","Female","68 Fieldstone Hill"));
        mentorList.add(new Mentor("Kleon","Bogaert","kbogaerta","psunejftXVQ","1985-08-30","kbogaerta@dyndns.org","Male","58549 Miller Circle"));
        mentorList.add(new Mentor("Terrence","Jendas","tjendasb","7pV2CHa","1986-06-12","tjendasb@storify.com","Male","63108 Cambridge Terrace"));
        mentorList.add(new Mentor("Michail","Harriskine","mharriskinec","RAXT0zo","1982-11-28","mharriskinec@tuttocitta.it","Female","2 Moulton Drive"));
        mentorList.add(new Mentor("Lennard","Cescon","lcescond","SeGSCjSU9Nt","1994-05-02","lcescond@irs.gov","Male","4570 Gina Junction"));
        mentorList.add(new Mentor("Killie","Polly","kpollye","Yl010Xw","1977-01-20","kpollye@ibm.com","Female","5101 Milwaukee Junction"));
        mentorList.add(new Mentor("Lee","Grichukhanov","lgrichukhanovf","OQXpPYQHPnZY","1993-04-22","lgrichukhanovf@acquirethisname.com","Male","9883 Scoville Drive"));
        mentorList.add(new Mentor("Kristian","Gever","kgeverg","hW0sM06","1973-04-09","kgeverg@bloglovin.com","Female","408 Main Plaza"));
        mentorList.add(new Mentor("Giffard","Raftery","grafteryh","0OGwoGzCMxf","1984-03-05","grafteryh@usa.gov","Female","1053 Melby Drive"));
        mentorList.add(new Mentor("Ryan","Oboy","roboyi","2IMWoe8JYFPY","1972-08-28","roboyi@multiply.com","Female","9289 Esker Junction"));
        mentorList.add(new Mentor("Matt","Egle","meglej","RaU3Zf1","1980-04-23","meglej@reddit.com","Female","59274 Caliangt Hill"));
        mentorList.add(new Mentor("Vin","Petchey","vpetcheyk","qWgioZ","1975-03-23","vpetcheyk@wikimedia.org","Male","23 Boyd Street"));
        mentorList.add(new Mentor("Dorie","Gabbitas","dgabbitasl","Cw0wQ46HR","1977-09-21","dgabbitasl@upenn.edu","Male","20 David Crossing"));
        mentorList.add(new Mentor("Matthieu","Caesar","mcaesarm","X1vzj77mB","1974-02-28","mcaesarm@stanford.edu","Female","32 Eagle Crest Way"));
        mentorList.add(new Mentor("Ignaz","Sweed","isweedn","qXmWVj8ZGpGD","1995-05-11","isweedn@merriam-webster.com","Female","98 Butterfield Avenue"));
        mentorList.add(new Mentor("Aylmar","Larter","alartero","uPycJA4w","1993-04-12","alartero@ovh.net","Male","800 Arrowood Junction"));
        mentorList.add(new Mentor("Jamie","Pocklington","jpocklingtonp","r9KWxlNrtt","1986-08-06","jpocklingtonp@xing.com","Female","392 Lakewood Gardens Junction"));
        mentorList.add(new Mentor("Enos","Bushel","ebushelq","iulcQPf2J","1973-09-10","ebushelq@home.pl","Male","551 Ramsey Drive"));
        mentorList.add(new Mentor("Pierson","Raw","prawr","bhy3rMj8xhb","1981-03-14","prawr@yandex.ru","Female","68 Upham Avenue"));
        mentorList.add(new Mentor("Karlik","Carmont","kcarmonts","tOgy1V","1994-11-08","kcarmonts@sbwire.com","Female","42756 Meadow Vale Terrace"));
        mentorList.add(new Mentor("Wait","Gobel","wgobelt","xUxjpXrLSklg","1980-04-15","wgobelt@biglobe.ne.jp","Female","4 Erie Park"));
        mentorList.add(new Mentor("Burty","Berkeley","bberkeleyu","kfD3ilPor","1992-11-17","bberkeleyu@is.gd","Female","1394 Springview Court"));
        mentorList.add(new Mentor("Olav","Shewsmith","oshewsmithv","AtlWfIhjYm","1985-07-16","oshewsmithv@bbc.co.uk","Female","79374 Superior Avenue"));
        mentorList.add(new Mentor("Dieter","Ravenscroftt","dravenscrofttw","qeW5Zcxj53iL","1983-01-13","dravenscrofttw@tinypic.com","Female","3679 Luster Circle"));
        mentorList.add(new Mentor("Galen","Hunton","ghuntonx","VlsfWDJ","1985-11-01","ghuntonx@friendfeed.com","Female","97 Warner Place"));
        mentorList.add(new Mentor("Ronald","Danielovitch","rdanielovitchy","JBBCWfx","1986-06-19","rdanielovitchy@tamu.edu","Female","04 Fisk Drive"));
        mentorList.add(new Mentor("Sullivan","Barthelmes","sbarthelmesz","oEWNaim","1982-06-30","sbarthelmesz@epa.gov","Male","83 Fairfield Crossing"));
        mentorList.add(new Mentor("Geordie","Eary","geary10","sgTOu3Rd","1974-03-14","geary10@cisco.com","Female","0190 Leroy Center"));
        mentorList.add(new Mentor("Kristos","Vittet","kvittet11","KaQDyEsv","1982-03-04","kvittet11@php.net","Male","5094 Hermina Avenue"));
        mentorList.add(new Mentor("Heindrick","Beaconsall","hbeaconsall12","xqBSPn","1977-08-12","hbeaconsall12@ycombinator.com","Female","2972 Lotheville Road"));
        mentorList.add(new Mentor("Abran","Deeprose","adeeprose13","rtvsfluQPB","1982-09-19","adeeprose13@discuz.net","Male","943 Dakota Road"));
        mentorList.add(new Mentor("Adolpho","Brodest","abrodest14","4NC1wwTQI","1985-06-24","abrodest14@usa.gov","Female","5782 Gale Way"));
        mentorList.add(new Mentor("Eldin","Emer","eemer15","FiViIMQe","1985-09-05","eemer15@123-reg.co.uk","Female","9 Talisman Lane"));
        mentorList.add(new Mentor("Asa","Gehringer","agehringer16","2sbsZfP","1981-06-15","agehringer16@prlog.org","Male","521 Lakewood Gardens Court"));
        mentorList.add(new Mentor("Aldwin","Signorelli","asignorelli17","PfZUwgV6OTW","1991-11-05","asignorelli17@mayoclinic.com","Female","92925 Waubesa Center"));
        mentorList.add(new Mentor("Chane","Attaway","cattaway18","zVBi1w","1995-03-21","cattaway18@goo.gl","Male","82808 Glendale Plaza"));
        mentorList.add(new Mentor("Corbin","Nineham","cnineham19","GyIEhqi6","1990-04-30","cnineham19@theguardian.com","Male","68719 Mitchell Court"));
        mentorList.add(new Mentor("Conrado","Dugall","cdugall1a","tJLMSZBipek","1977-02-20","cdugall1a@umn.edu","Male","2863 Maywood Parkway"));
        mentorList.add(new Mentor("Ramsay","Rowantree","rrowantree1b","9Zdd60D","1977-07-23","rrowantree1b@cloudflare.com","Male","6 Myrtle Parkway"));
        mentorList.add(new Mentor("Erny","Leadbetter","eleadbetter1c","JcutZS8G","1991-06-11","eleadbetter1c@quantcast.com","Female","524 Loomis Street"));
        mentorList.add(new Mentor("Yulma","Bibey","ybibey1d","o9s6Moot92VJ","1992-05-13","ybibey1d@multiply.com","Male","7 Debs Trail"));
        mentorList.add(new Mentor("Lonnard","Candelin","lcandelin1e","jCMdt3oG6gZ","1976-01-20","lcandelin1e@twitter.com","Female","5 Arizona Trail"));
        mentorList.add(new Mentor("Morey","Crat","mcrat1f","08OiHHnuAK","1972-07-09","mcrat1f@china.com.cn","Male","5835 Pleasure Crossing"));
        mentorList.add(new Mentor("Art","Shercliff","ashercliff1g","Zb5xJIT","1985-01-23","ashercliff1g@fastcompany.com","Female","163 Butternut Road"));
        mentorList.add(new Mentor("Duky","Hegges","dhegges1h","RCtfL2YeVSqz","1982-10-12","dhegges1h@sfgate.com","Male","391 Amoth Park"));
        mentorList.add(new Mentor("Henri","Stairmond","hstairmond1i","BBalSzQyeL6","1979-05-23","hstairmond1i@google.com.br","Female","717 Golf View Circle"));
        mentorList.add(new Mentor("Edan","Gladdifh","egladdifh1j","wDTwX61EzR9","1972-01-21","egladdifh1j@si.edu","Male","92557 Anzinger Center"));
        mentorList.add(new Mentor("Tye","MacArthur","tmacarthur1k","z40yyLkEu","1993-10-14","tmacarthur1k@illinois.edu","Female","372 Grover Center"));
        mentorList.add(new Mentor("Benedick","Alwood","balwood1l","ohDWsCDg2DYI","1970-08-18","balwood1l@google.co.jp","Male","2186 Rieder Terrace"));
        mentorList.add(new Mentor("Miller","Pietsma","mpietsma1m","YelRGmma","1989-08-10","mpietsma1m@merriam-webster.com","Female","4643 High Crossing Street"));
        mentorList.add(new Mentor("Nat","Ide","nide1n","i9FrVY","1982-11-27","nide1n@pinterest.com","Female","1911 Eastwood Road"));
        mentorList.add(new Mentor("Winfred","Atterley","watterley1o","itG5cHFM","1976-02-12","watterley1o@skyrock.com","Male","2533 Meadow Ridge Circle"));
        mentorList.add(new Mentor("Hakeem","Talbot","htalbot1p","3f7H5YPo","1971-10-02","htalbot1p@mozilla.org","Female","53 Jana Street"));
        mentorList.add(new Mentor("Andonis","Ivashechkin","aivashechkin1q","QWrt4Hnbkt","1989-10-28","aivashechkin1q@instagram.com","Female","866 Talisman Center"));
        mentorList.add(new Mentor("Cort","Kittoe","ckittoe1r","XSeC5z0sAqCv","1977-11-08","ckittoe1r@ocn.ne.jp","Male","882 Havey Street"));
        mentorList.add(new Mentor("Ronnie","Dannell","rdannell1s","Auw43bbEjAV","1992-08-01","rdannell1s@addtoany.com","Female","4 Porter Avenue"));
        mentorList.add(new Mentor("Linus","Imlock","limlock1t","vHHNNzW","1985-07-30","limlock1t@ihg.com","Male","434 5th Court"));
        mentorList.add(new Mentor("Denys","Pee","dpee1u","abIt4UY7oQQ","1993-05-04","dpee1u@omniture.com","Female","3731 Mallory Circle"));
        mentorList.add(new Mentor("Early","Beavors","ebeavors1v","gwdilWxW","1983-08-20","ebeavors1v@elegantthemes.com","Female","05543 Mifflin Plaza"));
        mentorList.add(new Mentor("Munroe","Humphrey","mhumphrey1w","hty0p6Utipu","1972-04-02","mhumphrey1w@etsy.com","Female","285 Kensington Circle"));
        mentorList.add(new Mentor("Man","Davidwitz","mdavidwitz1x","92qvxg49qM","1984-08-27","mdavidwitz1x@constantcontact.com","Male","99210 Dapin Avenue"));
        mentorList.add(new Mentor("Feodor","Nabarro","fnabarro1y","36boQ9DjUD","1973-01-17","fnabarro1y@china.com.cn","Female","0 Maple Wood Hill"));
        mentorList.add(new Mentor("Elias","Dunan","edunan1z","nBJcpp","1971-10-20","edunan1z@webeden.co.uk","Male","405 Logan Plaza"));
        mentorList.add(new Mentor("Dmitri","Marwick","dmarwick20","E73TOytQIZ","1972-06-07","dmarwick20@cafepress.com","Male","152 Hermina Avenue"));
        mentorList.add(new Mentor("Yehudit","Southon","ysouthon21","Tw1TBnNDtf","1994-01-12","ysouthon21@umich.edu","Male","9 Scofield Trail"));
        mentorList.add(new Mentor("Garold","Attenbrough","gattenbrough22","P38S7Deg","1986-07-17","gattenbrough22@ucsd.edu","Male","6357 Maryland Place"));
        mentorList.add(new Mentor("Waldon","Snedden","wsnedden23","Jw30E1vIAC","1976-10-21","wsnedden23@hugedomains.com","Female","8641 Center Avenue"));
        mentorList.add(new Mentor("Sinclare","Muckle","smuckle24","v2G9Wm","1978-11-18","smuckle24@163.com","Female","910 Melby Lane"));
        mentorList.add(new Mentor("Basilius","Milington","bmilington25","ejgWdyT1E","1977-07-23","bmilington25@de.vu","Male","6706 Northfield Court"));
        mentorList.add(new Mentor("Wakefield","Knightsbridge","wknightsbridge26","GcRoKW","1984-03-11","wknightsbridge26@addtoany.com","Female","593 Forest Dale Parkway"));
        mentorList.add(new Mentor("Adams","Synnot","asynnot27","dc9hGX2em","1995-04-13","asynnot27@creativecommons.org","Female","010 Sauthoff Way"));
        mentorList.add(new Mentor("Raffarty","Simenot","rsimenot28","uGzN3502","1975-06-03","rsimenot28@woothemes.com","Male","08 Acker Court"));
        mentorList.add(new Mentor("Denys","Curuclis","dcuruclis29","auOMNjREC","1981-12-02","dcuruclis29@google.pl","Female","5314 Northport Plaza"));
        mentorList.add(new Mentor("Janek","Moyne","jmoyne2a","RKxj6yVHl5y","1974-01-02","jmoyne2a@usda.gov","Female","04236 Beilfuss Circle"));
        mentorList.add(new Mentor("Prinz","Pettit","ppettit2b","d4cFg32ilyf","1973-10-31","ppettit2b@craigslist.org","Female","87030 Maryland Junction"));
        mentorList.add(new Mentor("Thurstan","Rozalski","trozalski2c","oNzLflGj6a3","1989-11-23","trozalski2c@ameblo.jp","Female","564 Grayhawk Junction"));
        mentorList.add(new Mentor("Nappie","Seagood","nseagood2d","t7zofr2AR","1977-09-18","nseagood2d@archive.org","Male","20 Northport Plaza"));
        mentorList.add(new Mentor("Isador","Thackston","ithackston2e","HcimfC","1991-04-16","ithackston2e@newyorker.com","Female","145 High Crossing Drive"));
        mentorList.add(new Mentor("Farleigh","Olenikov","folenikov2f","qsdW0m5432","1980-10-13","folenikov2f@yandex.ru","Male","2 Scofield Park"));
        mentorList.add(new Mentor("Rolf","Cancellario","rcancellario2g","fnq2sqAz","1970-05-20","rcancellario2g@ovh.net","Female","01182 Transport Pass"));
        mentorList.add(new Mentor("Ashton","Whyte","awhyte2h","7FMpBMq2D","1972-12-30","awhyte2h@yahoo.com","Male","959 Miller Alley"));
        mentorList.add(new Mentor("Heinrik","Padilla","hpadilla2i","q8chXWQegBaU","1991-05-28","hpadilla2i@ted.com","Male","58 Del Sol Parkway"));
        mentorList.add(new Mentor("Kipp","Keetley","kkeetley2j","xWVjdpZc6U","1995-03-13","kkeetley2j@virginia.edu","Male","54 Pennsylvania Junction"));
        mentorList.add(new Mentor("Ozzy","Bangley","obangley2k","WSFWYq0Yt","1983-07-09","obangley2k@ihg.com","Female","0 Hoffman Terrace"));
        mentorList.add(new Mentor("Wittie","Kwietek","wkwietek2l","qydx39Gt7dz","1983-11-29","wkwietek2l@a8.net","Male","3 Orin Terrace"));
        mentorList.add(new Mentor("Tedman","Flute","tflute2m","QpgGYdt","1970-02-23","tflute2m@behance.net","Female","60 La Follette Terrace"));
        mentorList.add(new Mentor("Murry","Batchelar","mbatchelar2n","rxkjHE6P466R","1985-12-14","mbatchelar2n@guardian.co.uk","Female","395 Delladonna Crossing"));
        mentorList.add(new Mentor("Maxie","Baudassi","mbaudassi2o","rejFMWAXs","1995-08-11","mbaudassi2o@smh.com.au","Male","6858 Daystar Way"));
        mentorList.add(new Mentor("Mickey","Daltrey","mdaltrey2p","vczowkqazD","1980-09-17","mdaltrey2p@google.fr","Male","7 Oneill Place"));
        mentorList.add(new Mentor("Keenan","Skirlin","kskirlin2q","NTnzKgoP20B","1983-01-10","kskirlin2q@archive.org","Male","34 Hollow Ridge Parkway"));
        mentorList.add(new Mentor("Thaddus","Cridlan","tcridlan2r","zddmIn5z","1975-10-07","tcridlan2r@fema.gov","Male","773 Killdeer Lane"));
        mentorList.add(new Mentor("Nicky","Fromant","nfromant2s","NSLcMzDdz6yI","1989-03-28","nfromant2s@hatena.ne.jp","Female","56799 Novick Parkway"));
        mentorList.add(new Mentor("Frank","Unthank","funthank2t","gxyhkM9G","1986-08-16","funthank2t@yolasite.com","Female","570 Oxford Lane"));
        mentorList.add(new Mentor("Puff","Linneman","plinneman2u","1ElNfPv","1990-05-13","plinneman2u@nydailynews.com","Male","9102 Barby Pass"));
        mentorList.add(new Mentor("Brander","Drinan","bdrinan2v","Z1xhfEzK8","1978-12-09","bdrinan2v@oakley.com","Male","24460 Sullivan Plaza"));
        mentorList.add(new Mentor("Bartholemy","Litherborough","blitherborough2w","afqimt","1992-03-25","blitherborough2w@java.com","Female","1 Namekagon Center"));
        mentorList.add(new Mentor("Andros","Joule","ajoule2x","UjEFC5s","1984-10-24","ajoule2x@usda.gov","Female","21269 Garrison Way"));
        mentorList.add(new Mentor("Rodrique","Eaden","readen2y","WFdaYE8s6E","1972-11-07","readen2y@pagesperso-orange.fr","Male","0550 Algoma Drive"));
        mentorList.add(new Mentor("Thorpe","Grisbrook","tgrisbrook2z","lygmhWBuT","1990-03-04","tgrisbrook2z@statcounter.com","Male","5897 Butterfield Terrace"));
        mentorList.add(new Mentor("Hernando","Cotte","hcotte30","xno5qKJcjzU","1991-08-04","hcotte30@google.nl","Male","43 Leroy Pass"));
        mentorList.add(new Mentor("Javier","Wanden","jwanden31","dF3kQ5Lk4lc","1991-08-28","jwanden31@mapquest.com","Male","548 Schiller Junction"));
        mentorList.add(new Mentor("Ody","Le Marquis","olemarquis32","NivTjR","1983-04-03","olemarquis32@webs.com","Male","7156 Heath Place"));
        mentorList.add(new Mentor("Raimundo","Conti","rconti33","ry2juXG","1971-06-22","rconti33@yahoo.com","Female","19004 Golf Circle"));
        mentorList.add(new Mentor("Cristian","Huie","chuie34","qcuhmWZ97","1992-12-17","chuie34@123-reg.co.uk","Female","95752 Golf View Court"));
        mentorList.add(new Mentor("Gavin","McGarvie","gmcgarvie35","H7BT6OFIjEk","1971-08-10","gmcgarvie35@berkeley.edu","Female","33498 Monterey Parkway"));
        mentorList.add(new Mentor("Henrik","Gallimore","hgallimore36","YAlW0y3","1994-03-30","hgallimore36@omniture.com","Male","69 Beilfuss Trail"));
        mentorList.add(new Mentor("Lefty","McKinney","lmckinney37","Vp4mKkGS0UU","1993-07-24","lmckinney37@myspace.com","Male","76324 Londonderry Drive"));
        mentorList.add(new Mentor("Saleem","Georgius","sgeorgius38","kMHQfj","1970-06-08","sgeorgius38@deliciousdays.com","Male","6 Forster Center"));
        mentorList.add(new Mentor("Dov","Bonnor","dbonnor39","786D7Mq","1990-07-27","dbonnor39@example.com","Male","800 Fairview Court"));
        mentorList.add(new Mentor("Marv","Giovanardi","mgiovanardi3a","FjAaaVIUA1oY","1982-05-22","mgiovanardi3a@netscape.com","Female","5729 Eagle Crest Park"));
        mentorList.add(new Mentor("Kelwin","Jesteco","kjesteco3b","OKI9IaoKpd","1983-11-10","kjesteco3b@pinterest.com","Male","377 Eagle Crest Way"));
        mentorList.add(new Mentor("Tomaso","Mercy","tmercy3c","WxGVHxal7b","1980-02-09","tmercy3c@google.it","Female","98 Nelson Center"));
        mentorList.add(new Mentor("Tades","Amer","tamer3d","RivUMU4MVtK","1988-10-03","tamer3d@etsy.com","Male","9013 Cambridge Center"));
        mentorList.add(new Mentor("Alexei","Koba","akoba3e","c6XAOxYjs","1974-05-01","akoba3e@lulu.com","Female","0237 Brentwood Street"));
        mentorList.add(new Mentor("Rodge","Lindenbaum","rlindenbaum3f","aoqyy03PexQ","1974-05-30","rlindenbaum3f@wired.com","Female","6870 Loftsgordon Road"));
        mentorList.add(new Mentor("Alf","Cuddon","acuddon3g","mhXzU9B2S6eU","1993-09-26","acuddon3g@51.la","Male","04967 Washington Park"));
        mentorList.add(new Mentor("Garrard","Goodship","ggoodship3h","WTbfi4dge","1993-05-18","ggoodship3h@simplemachines.org","Male","3 David Park"));
        mentorList.add(new Mentor("Fin","Mulbry","fmulbry3i","I4brsBg0AGlg","1988-09-14","fmulbry3i@smh.com.au","Female","454 Loeprich Avenue"));
        mentorList.add(new Mentor("Jamison","Foston","jfoston3j","SnMQKOxg","1977-10-14","jfoston3j@ustream.tv","Female","77298 Sunnyside Crossing"));
        mentorList.add(new Mentor("Levin","Dunphie","ldunphie3k","39cNuPsYcDYr","1987-07-17","ldunphie3k@liveinternet.ru","Female","4497 Butternut Junction"));
        mentorList.add(new Mentor("Gabbie","Roffey","groffey3l","RQRCLx","1987-06-07","groffey3l@aboutads.info","Male","63552 Fallview Court"));
        mentorList.add(new Mentor("Christopher","Doctor","cdoctor3m","wvkZzKFAm","1989-09-24","cdoctor3m@aol.com","Male","063 Fairfield Terrace"));
        mentorList.add(new Mentor("Rodney","Coulthurst","rcoulthurst3n","BPxk4ml","1991-02-25","rcoulthurst3n@istockphoto.com","Female","75998 Mandrake Avenue"));
        mentorList.add(new Mentor("Devland","Egglestone","degglestone3o","25jkoGTV","1979-03-09","degglestone3o@washingtonpost.com","Female","39111 Susan Plaza"));
        mentorList.add(new Mentor("Rafaellle","Skayman","rskayman3p","kXDevFxer7I","1990-10-09","rskayman3p@gravatar.com","Male","7 Mcbride Alley"));
        mentorList.add(new Mentor("Joseph","Good","jgood3q","sCs5qzS","1971-10-24","jgood3q@reddit.com","Female","4 Kedzie Park"));
        mentorList.add(new Mentor("Skyler","Delhay","sdelhay3r","5gKBqG","1985-11-18","sdelhay3r@marriott.com","Male","0 Weeping Birch Parkway"));
        mentorList.add(new Mentor("Niven","Hambleton","nhambleton3s","EvqLjvf5f","1990-12-07","nhambleton3s@ezinearticles.com","Male","32092 Dexter Park"));
        mentorList.add(new Mentor("Mischa","Iannelli","miannelli3t","y5wvMUy","1983-05-09","miannelli3t@youku.com","Male","186 Monica Street"));
        mentorList.add(new Mentor("Cece","Ormes","cormes3u","k99zDp","1983-11-01","cormes3u@webeden.co.uk","Male","688 South Lane"));
        mentorList.add(new Mentor("Schuyler","Pavis","spavis3v","oarST7m0Q","1987-04-08","spavis3v@reddit.com","Female","5428 Bashford Junction"));
        mentorList.add(new Mentor("Seth","Lead","slead3w","yknZWBGYy","1984-07-14","slead3w@aboutads.info","Male","482 Marquette Terrace"));
        mentorList.add(new Mentor("Ebenezer","Franceschielli","efranceschielli3x","4IDEdQq9N","1987-05-28","efranceschielli3x@a8.net","Male","955 Shasta Lane"));
        mentorList.add(new Mentor("Rodney","Dossit","rdossit3y","k6dhdnKa9","1981-11-12","rdossit3y@blinklist.com","Male","0 Helena Court"));
        mentorList.add(new Mentor("Lane","Mingauld","lmingauld3z","NTOamLUJUIV","1988-07-18","lmingauld3z@imgur.com","Male","713 Onsgard Junction"));
        mentorList.add(new Mentor("Nick","Kayne","nkayne40","apFAtX2V","1989-06-16","nkayne40@privacy.gov.au","Male","6 Hintze Center"));
        mentorList.add(new Mentor("Austin","Sola","asola41","bMQLOhkLs","1993-11-22","asola41@merriam-webster.com","Male","1814 Chive Street"));
        mentorList.add(new Mentor("Husain","Borres","hborres42","f5ASIf00Z","1990-08-06","hborres42@state.tx.us","Female","4 Hagan Pass"));
        mentorList.add(new Mentor("Haskel","Servant","hservant43","Gug1mi1mf4","1992-12-28","hservant43@yahoo.co.jp","Female","4 Heffernan Lane"));
        mentorList.add(new Mentor("Sherlock","Geaney","sgeaney44","WZE8ZgPr4q","1980-08-18","sgeaney44@nymag.com","Female","6930 Hollow Ridge Terrace"));
        mentorList.add(new Mentor("Flin","Bodycote","fbodycote45","6R6XU1waU6y","1988-07-14","fbodycote45@auda.org.au","Female","8749 Maywood Plaza"));
        mentorList.add(new Mentor("Hirsch","Blunkett","hblunkett46","vdUXJYXVeAi","1994-02-14","hblunkett46@statcounter.com","Female","81996 Rowland Terrace"));
        mentorList.add(new Mentor("Jory","Bendare","jbendare47","WdDYLqlz","1989-07-05","jbendare47@utexas.edu","Male","24685 Eagle Crest Hill"));
        mentorList.add(new Mentor("Wolfgang","Bracco","wbracco48","4dnsYaYlx","1993-04-26","wbracco48@booking.com","Female","0 Pond Junction"));
        mentorList.add(new Mentor("Rodrick","Ager","rager49","wjW7ERlB","1971-05-29","rager49@reuters.com","Male","7 Village Green Drive"));
        mentorList.add(new Mentor("Killian","Lortzing","klortzing4a","YJNyHgQDduF","1982-04-13","klortzing4a@opera.com","Female","03 Prentice Park"));
        mentorList.add(new Mentor("Gabriele","Scopes","gscopes4b","zv3sebhF","1978-01-12","gscopes4b@flavors.me","Male","4 Bluestem Hill"));
        mentorList.add(new Mentor("Jory","Catlow","jcatlow4c","CE9Dzunng","1993-03-22","jcatlow4c@cyberchimps.com","Female","5464 Nelson Crossing"));
        mentorList.add(new Mentor("Garrard","Ehlerding","gehlerding4d","oHQoqNKqgQ","1986-10-24","gehlerding4d@wsj.com","Female","154 Victoria Avenue"));
        mentorList.add(new Mentor("Nickola","Millea","nmillea4e","1TwueGwk","1984-05-06","nmillea4e@uol.com.br","Female","5 Buell Trail"));
        mentorList.add(new Mentor("Thacher","Gerler","tgerler4f","x4O2Lko","1980-05-13","tgerler4f@exblog.jp","Female","70 Lakeland Avenue"));
        mentorList.add(new Mentor("Bram","Skentelbery","bskentelbery4g","JmqXXp0mQ5OY","1989-03-30","bskentelbery4g@cyberchimps.com","Male","60 Coolidge Way"));
        mentorList.add(new Mentor("George","Bankes","gbankes4h","sJmRJeWx6opt","1994-05-30","gbankes4h@constantcontact.com","Female","82 Elka Crossing"));
        mentorList.add(new Mentor("Zacharie","Poytheras","zpoytheras4i","ccyPNhril","1992-05-27","zpoytheras4i@sfgate.com","Male","43 Menomonie Trail"));
        mentorList.add(new Mentor("Sebastien","Danielsohn","sdanielsohn4j","3Xd8EQPm5D","1978-07-01","sdanielsohn4j@hao123.com","Female","395 Blackbird Place"));
        mentorList.add(new Mentor("Law","Haresnape","lharesnape4k","X3W5Nx9AHWo6","1988-07-01","lharesnape4k@gnu.org","Female","3707 Merry Point"));
        mentorList.add(new Mentor("Josh","Brion","jbrion4l","QNSwYQwXyPZ","1979-08-16","jbrion4l@salon.com","Male","460 Moland Lane"));
        mentorList.add(new Mentor("Eward","Studholme","estudholme4m","3WYs5JdlGSD","1991-03-08","estudholme4m@latimes.com","Female","58 Roxbury Drive"));
        mentorList.add(new Mentor("Ingram","Sircombe","isircombe4n","m1Rn6v","1970-06-19","isircombe4n@oakley.com","Male","4524 Rieder Pass"));
        mentorList.add(new Mentor("Barnie","Fist","bfist4o","CRlRifxi5","1975-04-27","bfist4o@github.com","Male","3 Schiller Point"));
        mentorList.add(new Mentor("Sigismundo","Beavon","sbeavon4p","feQhjjP3gWo","1989-11-15","sbeavon4p@w3.org","Female","63 Drewry Avenue"));
        mentorList.add(new Mentor("Standford","Geroldi","sgeroldi4q","h3Gdynjl4ES","1993-12-11","sgeroldi4q@about.me","Female","06028 Springview Alley"));
        mentorList.add(new Mentor("Duncan","Girone","dgirone4r","qmYUo6olYy","1976-01-11","dgirone4r@moonfruit.com","Male","820 Golf Plaza"));
        mentorList.add(new Mentor("Randi","Michie","rmichie4s","z7nobKP37","1980-02-12","rmichie4s@privacy.gov.au","Male","83480 Helena Place"));
        mentorList.add(new Mentor("Norrie","Shorie","nshorie4t","QkPBunvvSukZ","1985-05-30","nshorie4t@bloglovin.com","Female","3971 Morningstar Crossing"));
        mentorList.add(new Mentor("Reider","Anstee","ranstee4u","ofkrpSnDeAto","1978-04-20","ranstee4u@fema.gov","Male","0615 Blackbird Parkway"));
        mentorList.add(new Mentor("Gerek","McEvoy","gmcevoy4v","3Yclp81ueQ5","1970-07-11","gmcevoy4v@devhub.com","Male","0 Utah Plaza"));
        mentorList.add(new Mentor("Horatius","Ivanikhin","hivanikhin4w","1rxH9VE","1986-02-24","hivanikhin4w@deviantart.com","Male","38 Bobwhite Trail"));
        mentorList.add(new Mentor("Nappie","Jiras","njiras4x","7Fg6Gz5","1978-11-07","njiras4x@imdb.com","Male","42754 Myrtle Junction"));
        mentorList.add(new Mentor("Aaron","Klamp","aklamp4y","gOUWhGSL1iE","1994-08-25","aklamp4y@wunderground.com","Female","8 Sheridan Plaza"));
        mentorList.add(new Mentor("Thibaud","Ryles","tryles4z","zRxIXoElh","1979-07-27","tryles4z@pagesperso-orange.fr","Female","71 Caliangt Point"));
        mentorList.add(new Mentor("Rudolph","Hathaway","rhathaway50","hFqnSm","1983-01-02","rhathaway50@infoseek.co.jp","Female","542 Morningstar Avenue"));
        mentorList.add(new Mentor("Vachel","Townes","vtownes51","MlyLg5","1971-08-03","vtownes51@pinterest.com","Male","6 7th Point"));
        mentorList.add(new Mentor("Brad","Byllam","bbyllam52","bskXkbGyV","1988-08-24","bbyllam52@spiegel.de","Female","862 Marcy Park"));
        mentorList.add(new Mentor("Tucker","Armell","tarmell53","OszpPJNDUh","1988-12-13","tarmell53@dailymotion.com","Female","6652 Melby Circle"));
        mentorList.add(new Mentor("Raimund","Oakeshott","roakeshott54","mcnjWw5XZIxq","1973-07-24","roakeshott54@github.com","Female","25375 Redwing Terrace"));
        mentorList.add(new Mentor("Kennett","Baumadier","kbaumadier55","gxRF4o","1975-10-02","kbaumadier55@myspace.com","Male","9129 Manufacturers Road"));
        mentorList.add(new Mentor("Alfred","Pandya","apandya56","ACYPBG","1989-05-29","apandya56@washingtonpost.com","Male","59 Basil Crossing"));
        mentorList.add(new Mentor("Port","Crannell","pcrannell57","TZ8VIor12u","1970-08-27","pcrannell57@omniture.com","Female","7939 Carberry Way"));
        mentorList.add(new Mentor("Birk","Clemens","bclemens58","mBUM1B8CfP","1982-11-14","bclemens58@unicef.org","Female","850 Waywood Place"));
        mentorList.add(new Mentor("Derrik","Conaghy","dconaghy59","01mp4KVVij","1982-10-19","dconaghy59@ucoz.ru","Male","15702 Hovde Drive"));
        mentorList.add(new Mentor("Ashley","Cayet","acayet5a","8gCxFkKK","1977-12-31","acayet5a@moonfruit.com","Male","1247 Norway Maple Circle"));
        mentorList.add(new Mentor("Sergio","Gurner","sgurner5b","mqlxc9Iea5jN","1992-04-13","sgurner5b@squarespace.com","Male","7993 American Junction"));
        mentorList.add(new Mentor("Matthaeus","Malek","mmalek5c","VJGf2aVd9yt","1987-04-21","mmalek5c@nps.gov","Female","6 Morningstar Trail"));
        mentorList.add(new Mentor("Field","Snell","fsnell5d","XzMXqdZLem","1970-03-27","fsnell5d@sogou.com","Male","266 Florence Pass"));
        mentorList.add(new Mentor("Son","Skone","sskone5e","KKM9wsKxVh","1982-05-23","sskone5e@goo.ne.jp","Male","5297 Shasta Pass"));
        mentorList.add(new Mentor("Walton","Crapper","wcrapper5f","kV7UnDL","1972-12-16","wcrapper5f@prweb.com","Male","172 Hoffman Street"));
        mentorList.add(new Mentor("Mohandis","Dayer","mdayer5g","CyXGnZs0i","1992-06-07","mdayer5g@xrea.com","Female","42438 Village Plaza"));
        mentorList.add(new Mentor("Zebulon","Hegel","zhegel5h","ujtbGu0NqQ","1989-10-13","zhegel5h@prlog.org","Male","306 Sutteridge Terrace"));
        mentorList.add(new Mentor("Thaddus","Balden","tbalden5i","E6bO1C1","1990-12-27","tbalden5i@prnewswire.com","Male","83 Morrow Point"));
        mentorList.add(new Mentor("Philbert","Ecclestone","pecclestone5j","7WJzoG","1978-12-01","pecclestone5j@wikimedia.org","Female","01 International Pass"));*/

        //userService.register("Mitko06","admin123","admin123","Mitko","Gurbanski", Role.MENTOR);

    }
}